### ISSUE TITLE
Rust crate usage

### ISSUE THREAD

**Issue by mdbond** [plasma-umass/ChatDBG#42]
The instructions for Rust support don't quite work because the version of Rust crate `chatdbg` on `crates.io` lacks one line in `lib.rs` that's present in the ChatDBG GitHub repo:

```
pub use chatdbg_macros::main;
```

As a result,

```
#[chatdbg::main]
```

gives a compiler error because it doesn't refer to `chatdbg_macros::main`.

Suggested fixes:
* Provide new version of `chatdbg` on `crates.io` OR
* Change README's Rust instructions so `Cargo.toml` imports `chatdbg_macros` (instead of `chatdbg`) and main file uses `#[chatdbg_macros::main]` annotation (instead of  `#[chatdbg::main]` annotation)

ChatDBG is cool work! Thanks for making it available!

**Comment by nicovank** [comment]
Thanks for the report!

Emery just managed to push the updated version to crates.io, `chatdbg@0.6.2`. I tested locally and it seemed to have fixed the issue. I have been trying to make this automatic along with the PyPI release, ran into some permission issues.

I also think we should maybe publish a single crate instead of two and make one an alias of the other but that's another issue.

**Comment by nicovank** [comment]
Closing this, Rust crates should now update automatically after each release 👍

Talked with Noah about merging the two, but it looks like it is recommended and common practice to have two for those macro crates, at least as of today.
