### ISSUE TITLE
use GDB but some command is not allowed

### ISSUE THREAD

**Issue by ydhuyong** [plasma-umass/ChatDBG#49]
while I try to use it with ubuntu 22.04/gdb to debug the sample cpp code, I meet these output. What trouble me is that these command can run correct while I typing it, but the tools tell me that "Command is not allowed". Here is the answer:
![Screenshot from 2024-09-18 19-22-01](https://github.com/user-attachments/assets/4fa39825-1ac9-4079-86a4-0578eb51ae6b)

**Comment by nicovank** [comment]
What’s happening is the tool is telling ChatGPT (rather than you) that the command is not available. This is a new feature: we sanitize ChatGPT commands to make sure it doesn’t try to harm your computer.

Since these models are trained to not output any harmful code this is unlikely unless you directly ask it, you can set `CHATDBG_UNSAFE=1` in the environment to disable sanitizing (and run in Docker if you want to be extra safe). 

In this specific case `info locals` it looks like we should have been whitelisting it, I’ll take a look later today.

**Comment by nicovank** [comment]
The GDB `info` command seems safe across all subcommands, so does '.' in print expressions.
Allowed both of those in e8e80e0c1b07684c49d50effa0a13330092e1b63 and 6653d2c9ce3ce4bff707c98cea96faf02092112d.

You should be able to enable unsafe mode within a ChatDBG dialog to retry (`config --unsafe` I think). @khlevin can you confirm?

We should print a warning if a potentially unsafe command is blocked by ChatDBG to let the user know, and tell them how to enable unsafe mode right there. Something like this:
```
Warning: One or more debugger commands were blocked as potentially unsafe.
Warning: You can disable sanitizing with `...` and try again at your own risk.
```

@khlevin is taking care of this, then this issue can be closed. We'll issue a new release shortly after.
